-- MySQL-specific syntax

/* Modelagem básica */

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTES(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF CHAR(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);


INSERT INTO CLIENTES VALUES('JOAO','M','JOAO@GMAIL.COM','988638273','22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('CELIA','F','CELIA@GMAIL.COM','541521456','25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('JORGE','M',NULL,'885755896','58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

INSERT INTO CLIENTES(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696','887774856');

RENAME TABLE CLIENTES TO CLIENTE;

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM','85548962','548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR','7745828','66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');


SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT SEXO, NOME AS CLIENTE FROM CLIENTE 
WHERE SEXO = 'F';

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME AS CLIENTE, ENDERECO, CPF FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

SHOW DATABASES;

USE PROJETO;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS"FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT SEXO, COUNT(*) AS "NUMERO DE CLIENTES DE CADA SEXO" FROM CLIENTE
GROUP BY SEXO;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = "noemail"
WHERE EMAIL IS NULL;

UPDATE CLIENTE
SET EMAIL = "jorjim_mulherengo@yahoo.com.br"
WHERE NOME = "Jorge";

UPDATE CLIENTE
SET EMAIL = "lilian.flores@yahoo.com.br"
WHERE NOME = "Lilian";

SELECT NOME, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE 
WHERE NOME = "ANA";

SELECT COUNT(*) AS "REGISTROS" FROM CLIENTE;

SELECT COUNT(*) AS "NUMERO DE REGISTROS QUE SERAO DELETADOS" FROM CLIENTE
WHERE NOME = "ANA";

DELETE FROM CLIENTE
WHERE NOME = "ANA";

INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ("CARLA ZAMBELI", "F", "RUA DOS BOBOS NUMERO 0", "91234-5678", "09505983212")

SELECT * FROM CLIENTE
WHERE EMAIL IS NULL;

UPDATE CLIENTE
SET EMAIL = "CARALHA.ZABELL@OUTVLOOK.MOC"
WHERE NOME = "CARLA";

SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = "CARALHA.ZABELL@OUTVLOOK.MOC"
WHERE NOME = "CARLA ZAMBELI";

DELETE FROM CLIENTE
WHERE CPF = "7745828";


/* FORMAS NORMAIS

PRIMEIRA FORMA NORMAL:
    a) TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

    b) TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA -> QUANDO O CAMPO FOR DIVISIVEL -> FAMÍLIAS DISTINTAS

    c) TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO (CHAVE PRIMARIA/PRIMARY KEY)

    (0, 1)
    (0, N)
    (1, 1)
    (1, 1)

    O PRIMEIRO NUMERO DO PAR DIZ RESPEITO À OBRIGATORIEDADE E O SEGUNDO À CARDINALIDADE (REFERENTE AO MÁXIMO DE VALORES POSSIVEIS)

*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM("M", "F") NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(11) UNIQUE
);



































