-- MySQL-specific syntax

-- 1 – Trazer todos os dados.
-- 2 – Trazer o nome do livro e o nome da editora
-- 3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino.
-- 4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.
-- 5 – Trazer os valores dos livros das editoras de São Paulo.
-- 6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).


CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
    NOME_DO_LIVRO VARCHAR(30),
    NOME_DO_AUTOR VARCHAR(30),
    SEXO_DO_AUTOR CHAR(1),
    NUMERO_DE_PAGINAS SMALLINT(4),
    NOME_DA_EDITORA VARCHAR(30),
    VALOR_DO_LIVRO SMALLINT(4),
    ESTADO_DA_EDITORA CHAR(2),
    ANO_PUBLICAÇÃO CHAR(4)
);


ALTER TABLE LIVROS
MODIFY COLUMN VALOR_DO_LIVRO FLOAT(5,2);

ALTER TABLE LIVROS
MODIFY COLUMN SEXO_DO_AUTOR CHAR(9);

INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Cavaleiro Real','Ana Claudia','Feminino',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('SQL para leigos','João Nunes','Masculino',450,'Addison',98,'SP', 2018);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Receitas Caseiras','Celia Tavares','Feminino',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Pessoas Efetivas','Eduardo Santos','Masculino',390,'Beta',78.99,'RJ',2018);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Habitos Saudáveis','Eduardo Santos','Masculino',630,'Beta',150.98,'RJ',2019);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('A Casa Marrom','Hermes Macedo','Masculino',250,'Bubba',60,'MG', 2016);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Estacio Querido','Geraldo Francisco','Masculino',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Pra sempre amigas','Leda Silva','Feminino',510,'Insignia',78.98,'ES',2011);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('Copas Inesqueciveis','Marco Alcantara','Masculino',200,'Larson',130.98,'RS',2018);
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA, ANO_PUBLICAÇÃO) VALUES('O poder da mente','Clara Mafra','Feminino',120,'Continental',56.58,'SP',2017);

-- 1

SELECT * FROM LIVROS;

-- 2

SELECT NOME_DO_AUTOR AS AUTOR, NOME_DA_EDITORA AS EDITORA FROM LIVROS;

-- 3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino.

SELECT NOME_DO_AUTOR AS AUTOR, ESTADO_DA_EDITORA AS UF FROM LIVROS
WHERE SEXO_DO_AUTOR = "Masculino";

-- 4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.

SELECT NOME_DO_LIVRO AS LIVRO, NUMERO_DE_PAGINAS AS "NUMERO DE PAGINAS" FROM LIVROS
WHERE SEXO_DO_AUTOR = "Feminino";

-- 5 – Trazer os valores dos livros das editoras de São Paulo.

SELECT VALOR_DO_LIVRO AS "Preço" FROM LIVROS
WHERE ESTADO_DA_EDITORA = "SP";

-- 6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).

SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = "Masculino" AND (ESTADO_DA_EDITORA = "SP" OR ESTADO_DA_EDITORA = "RJ");